### ISSUE TITLE
Wrong alias in docker-compose.yml

### ISSUE THREAD

**Issue by rekn64** [kitsunekyo/ISP-SpeedTest-Logger#36]
api seems unable to connect to the db. i think the problem is the wrong alias used in docker-compose.yml file

suggestion:
change 
MONGODB_CONNECTION_STRING=mongodb://isp-db:27017/isp 
to 
MONGODB_CONNECTION_STRING=mongodb://db:27017/isp

and add the option

        links:
            - db

to the api service.

also change the environment in example.env to
MONGODB_CONNECTION_STRING=mongodb://db:27017/isp

furthermore:

example.env seems to miss the NODE_ENV enviroment

suggestion add to example.env
NODE_ENV=production

**Comment by kitsunekyo** [comment]
**db connection**
should be fixed in commit `b929359`

**link**
link is unnecessary, as within docker all services are reachable by service name by default. link just gives you the option to configure additional aliases.

**node_env in example.env**
not required, as we only test for `NODE_ENV === "production"`, and it assumes development for anything else.
the example.env should mimic the development environment by default, and should be adapted by whoever is deploying, to fit the required env.
